" Vim configuration
" Author : Alexis Couronne - http://skitoo.net

"-------------------------------------------------------------------------------
call plug#begin('~/.vim/plugged')

" Indispensables plugins
Plug 'vim-airline/vim-airline'
Plug 'vim-airline/vim-airline-themes'
Plug 'ctrlpvim/ctrlp.vim'
Plug 'scrooloose/nerdtree'
Plug 'scrooloose/syntastic'
Plug 'scrooloose/nerdcommenter'
Plug 'tpope/vim-fugitive'
Plug 'airblade/vim-gitgutter'
Plug 'tpope/vim-surround'
Plug 'majutsushi/tagbar'
Plug 'mattn/emmet-vim'
Plug 'Raimondi/delimitMate'
Plug 'Xuyuanp/nerdtree-git-plugin'
Plug 'Valloric/YouCompleteMe', { 'do': './install.sh' }
Plug 'ryanoasis/vim-devicons' " Need https://github.com/ryanoasis/nerd-fonts
Plug 'tiagofumo/vim-nerdtree-syntax-highlight'

" Themes
Plug 'flazz/vim-colorschemes'

" Languages
Plug 'klen/python-mode'
Plug 'sirtaj/vim-openscad'
Plug 'ElmCast/elm-vim'
Plug 'plasticboy/vim-markdown'
Plug 'pangloss/vim-javascript'
Plug 'mxw/vim-jsx'
Plug 'fatih/vim-go'
Plug 'rust-lang/rust.vim'
Plug 'ternjs/tern_for_vim', { 'do': 'npm install'}
Plug 'flowtype/vim-flow', { 'do': 'npm install -g flow-bin'}
Plug 'rodjek/vim-puppet'

call plug#end()

"-------------------------------------------------------------------------------
" General config
"

" Show the filename in the window titlebar
set title

" Enable line numbers
set number

" Show the cursor position
set ruler

" Do not wrap long lines
set nowrap

" Highlight current line
set cursorline

" Make tabs as wide as four spaces
set tabstop=2

" Autoindent to four spaces
set shiftwidth=2

" A soft-tab of four spaces
set softtabstop=2

" Hitting Tab in insert mode will produce the appropriate number of spaces
set expandtab

" Allow autoindent
set autoindent

" Allow smartindent
set smartindent

" Allow cindent
set cindent

" Disable swap files
set noswapfile

" Disable backup files
set nobackup

" The current buffer can be put to the background without writing to disk
set hidden

" Show invisible characters
set lcs=tab:▸\ ,trail:·,nbsp:_
set list

" Enable yank/cut/paste from clipboard
set clipboard+=unnamedplus

" Disable folding
set nofoldenable

" Set colorscheme
colorscheme Monokai

" Set guifont
set guifont=DroidSansMonoForPowerline\ Nerd\ Font\ Regular\ 11

" Allow transparency
hi Normal ctermfg=252 ctermbg=none
hi NonText ctermfg=59 ctermbg=none

" Turn on file type detection
filetype plugin indent on

" Check external changes
au FocusGained,BufEnter * :silent! checktime

" Disable arrow keys
nnoremap <up> <nop>
nnoremap <down> <nop>
nnoremap <left> <nop>
nnoremap <right> <nop>
inoremap <up> <nop>
inoremap <down> <nop>
inoremap <left> <nop>
inoremap <right> <nop>


" ------------------------------------------------------------------------------
" Specific language configs
"

" Javascript
autocmd FileType javascript set colorcolumn=101
autocmd FileType javascript.jsx setlocal sts=2 sw=2 ts=2

" Python
autocmd FileType python set colorcolumn=81
autocmd FileType python setlocal sts=4 sw=4 ts=4

"-------------------------------------------------------------------------------
" Pluggins config
"

" Vim-airline config
let g:airline#extensions#tabline#enabled = 1
let g:airline_powerline_fonts = 1
let g:airline_theme = 'badwolf'

" Nerdtree config
let NERDTreeIgnore = ['\.pyc$', '\.pyo$', '.git', '__pycache__', 'node_modules']
let NERDTreeShowHidden = 1
autocmd StdinReadPre * let s:std_in = 1
let g:NERDTreeIndicatorMapCustom = {
    \ "Modified"  : "✹",
    \ "Staged"    : "✚",
    \ "Untracked" : "✭",
    \ "Renamed"   : "➜",
    \ "Unmerged"  : "═",
    \ "Deleted"   : "✖",
    \ "Dirty"     : "✗",
    \ "Clean"     : "✔︎",
    \ "Unknown"   : "?"
    \ }
autocmd bufenter * if (winnr("$") == 1 && exists("b:NERDTree") && b:NERDTree.isTabTree()) | q | endif

" Nerdcommenter config
let g:NERDSpaceDelims = 1
let g:NERDCompactSexyComs = 1
let g:NERDDefaultAlign = 'left'
let g:NERDCommentEmptyLines = 1
let g:NERDTrimTrailingWhitespace = 1

" Vim-jsx config
let g:jsx_ext_required = 0  " enable jsx in .js files

" Syntastic config
set statusline+=%#warningmsg#
set statusline+=%{SyntasticStatuslineFlag()}
set statusline+=%*

let g:syntastic_always_populate_loc_list = 1
let g:syntastic_auto_loc_list = 1
let g:syntastic_check_on_open = 1
let g:syntastic_check_on_wq = 0

let g:syntastic_javascript_checkers = ['eslint', 'flow']
let g:syntastic_javascript_flow_exe = 'flow'

" Ctrlp config
set wildignore+=*/tmp/*,*/node_modules/*,*/dist/*,*.so,*.swp,*.zip,*.pyc,*.pyo

" Vim-fugitive config
set statusline+=%{fugitive#statusline()}

" Vim-devicons
let g:WebDevIconsUnicodeDecorateFolderNodes = 1
let g:DevIconsEnableFoldersOpenClose = 1
let g:WebDevIconsNerdTreeAfterGlyphPadding = ' '
if exists("g:loaded_webdevicons")
  call webdevicons#refresh()
endif
augroup devicons
  autocmd!
  autocmd FileType nerdtree setlocal nolist
  autocmd FileType nerdtree syntax match hideBracketsInNerdTree "\]" contained conceal containedin=ALL
  autocmd FileType nerdtree syntax match hideBracketsInNerdTree "\[" contained conceal containedin=ALL
  autocmd FileType nerdtree setlocal conceallevel=3
  autocmd FileType nerdtree setlocal concealcursor=nvic
augroup END

"-------------------------------------------------------------------------------
" Mapping
"

let mapleader = ","

" Save current file
nmap <C-s> :write<CR>

" Close VIM
nmap <leader>q :quit<CR>

" Close current buffer
nmap <C-q> :bd<CR>

" Toggle Tagbar
map <F2> :TagbarToggle<CR>

" Toggle NERDTree
map <F3> :NERDTreeToggle<CR>

" Sort selected lines
vmap <leader><F5> :sort<CR>

" Reload vim config file and refresh Airline
nmap <leader><F9> :so $MYVIMRC<CR>:AirlineRefresh<CR>

" Update all plugins
nmap <leader><F10> :PlugUpdate<CR>

"" Go to right buffers
nmap <leader>n  :bn<CR>

"" Go to left buffers
nmap <leader>b :bp<CR>

"" Go to the top window
nmap <leader>k :wincmd k<CR>

"" Go to the bottom window
nmap <leader>j :wincmd j<CR>

"" Go to the left window
nmap <leader>h :wincmd h<CR>

"" Go to the right window
nmap <leader>l :wincmd l<CR>

