#
# ZSH configuration
# Author : Alexis Couronne - http://skitoo.net
#

# Explicitly configured $PATH variable
export PATH="/bin:/usr/local/sbin:/usr/local/bin:/usr/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl:$HOME/cargo/bin:$HOME/.gem/ruby/2.3.0/bin:$HOME/.yarn/bin:$HOME/.local/bin:$HOME/.gem/ruby/2.6.0/bin:$HOME/.npm-global/bin:/snap/bin"

# Path to your oh-my-zsh installation.
export ZSH=$HOME/.oh-my-zsh

# Set name of the theme to load.
ZSH_THEME=powerlevel10k/powerlevel10k

# Which plugins would you like to load? (plugins can be found in ~/.oh-my-zsh/plugins/*)
# Example format: plugins=(rails git textmate ruby lighthouse)
plugins=(archlinux git github nvm npm docker docker-compose tmux tmuxinator kubectl mix yarn)

# Load oh-my-zsh script
source $ZSH/oh-my-zsh.sh

# Customise theme
ZSH_THEME_CLOUD_PREFIX='★'
PROMPT='%{$fg_bold[red]%}$ZSH_THEME_CLOUD_PREFIX %{$fg_bold[green]%}%p %{$fg[green]%}%c %{$fg_bold[cyan]%}$(git_prompt_info)%{$fg_bold[blue]%} % %{$reset_color%}'
ZSH_THEME_GIT_PROMPT_DIRTY="%{$fg[green]%}] %{$fg[yellow]%}▼%{$reset_color%}"

# Shell aliases
alias reload!='source ~/.zshrc'

if command -v exa &> /dev/null; then
  alias ls='exa --git'
  alias tree='ls --tree'
else
  echo "WARNING: exa is not installed"
  alias tree='tree -C'
fi

alias l='ls -la'
alias ll='ls -l'
alias la='ls -a'

alias ..='cd ..'
alias ...='cd ../..'
alias ....='cd ../../..'

alias grep='grep --color=auto'
alias df='df -h'
alias du='du -h -c'

alias vi='nvim'
alias vim='nvim'

if command -v htop &> /dev/null; then
  alias top='htop'
else
  echo "WARNING: htop is not installed"
fi

alias docker-clean='docker rmi $(docker images | grep "^<none>" | awk "{print $3}")'
alias fig='docker-compose'

alias localip='hostname -i'
alias publicip='dig +short myip.opendns.com @resolver1.opendns.com'
alias ips="ifconfig -a | perl -nle'/(\d+\.\d+\.\d+\.\d+)/ && print $1'"


if command -v tmux &> /dev/null; then
  alias ta='tmux attach'
  alias tls='tmux ls'
  alias tat='tmux attach -t'
  alias tns='tmux new-session -s'
else
  echo "WARNING: tmux is not installed"
fi

alias dl-music='youtube-dl -x --audio-format mp3 --audio-quality 0'

alias git-purge='git branch --merged | grep -v "\*" | grep -v "master" | xargs -n 1 git branch -d'

if command -v pacman &> /dev/null; then
  alias remove-orphans-packages='pacman -Rns $(pacman -Qtdq)'
fi


showLog () {
  git log --pretty=format:%s $1..$2 | awk '!/Merge/'
}


eval $(thefuck --alias)

# Custom exports
if [ -f /usr/bin/nvim ]; then
  export EDITOR='/usr/bin/nvim'
elif [ -f /snap/bin/nvim ]; then
  export EDITOR='/snap/bin/nvim'
elif [ -f /usr/bin/vim ]; then
  export EDITOR='/usr/bin/vim'
else
  export EDITOR='/usr/bin/vi'
fi

if [ -f /usr/bin/virtualenvwrapper.sh ]; then
  export WORKON_HOME=~/.virtualenvs
  source /usr/bin/virtualenvwrapper.sh
fi

if [ -f /usr/share/nvm/nvm.sh ]; then
  export NVM_DIR="$HOME/.nvm"
  source /usr/share/nvm/nvm.sh
  source /usr/share/nvm/bash_completion
fi

export ANDROID_HOME=/opt/android-sdk

export GOPATH=$HOME/go

# Put any proprietary or private functions/values in ~/.private file
if [ -f $HOME/.private ]; then
  source $HOME/.private
fi

[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

# To customize prompt, run `p10k configure` or edit ~/.p10k.zsh.
[[ -f ~/.p10k.zsh ]] && source ~/.p10k.zsh
