#
# ZSH configuration
# Author : Alexis Couronne - http://skitoo.net
#

# Explicitly configured $PATH variable
export PATH="/usr/local/sbin:/usr/local/bin:/usr/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl:$HOME/cargo/bin"

# Path to your oh-my-zsh installation.
export ZSH=$HOME/.oh-my-zsh

# Set name of the theme to load.
ZSH_THEME="cloud"

# Which plugins would you like to load? (plugins can be found in ~/.oh-my-zsh/plugins/*)
# Example format: plugins=(rails git textmate ruby lighthouse)
plugins=(git nvm docker docker-compose)

# Load oh-my-zsh script
source $ZSH/oh-my-zsh.sh

# Shell aliases
alias ls='ls --color'
alias l='ls -la'
alias ll='ls -l'
alias la='ls -a'

alias tree='tree -C'

alias grep='grep --color=auto'
alias df='df -h'
alias du='du -h -c'

alias vi='nvim'
alias vim='nvim'

alias top='htop'

alias docker-clean='docker rmi $(docker images | grep "^<none>" | awk "{print $3}")'
alias fig='docker-compose'

alias localip='hostname -i'
alias publicip='dig +short myip.opendns.com @resolver1.opendns.com'
alias ips="ifconfig -a | perl -nle'/(\d+\.\d+\.\d+\.\d+)/ && print $1'"
# Custom exports
if [ -f /usr/bin/nvim ]; then
  export EDITOR='/usr/bin/nvim'
fi

if [ -f /usr/bin/virtualenvwrapper.sh ]; then
  export WORKON_HOME=~/.virtualenvs
  source /usr/bin/virtualenvwrapper.sh
fi

if [ -f /usr/share/nvm/nvm.sh ]; then
  export NVM_DIR="$HOME/.nvm"
  source /usr/share/nvm/nvm.sh
  source /usr/share/nvm/bash_completion
fi

# Put any proprietary or private functions/values in ~/.private file
if [ -f $HOME/.private ]; then
  source $HOME/.private
fi
